package main_menu;

import Beranda.Beranda;
import form.Form_Login;
import Laporan.Laporan;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import menu.Menu_Makanan;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import menu.Meja;
import menu.Menu_Minuman;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.Painter;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author fauzanramadhana
 */
public class Main_Menu_ADMIN extends javax.swing.JFrame {

    public Main_Menu_ADMIN() {
        initComponents();
//        customizeComponents();
        execute();
        this.setSize(800, 650);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_header = new javax.swing.JPanel();
        jPanelGradient1 = new main_menu.JPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        pn_sideBar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        pn_content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_header.setBackground(new java.awt.Color(255, 255, 255));

        jPanelGradient1.setColorEnd(new java.awt.Color(125, 0, 5));
        jPanelGradient1.setColorStart(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Navbar (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanelGradient1Layout = new javax.swing.GroupLayout(jPanelGradient1);
        jPanelGradient1.setLayout(jPanelGradient1Layout);
        jPanelGradient1Layout.setHorizontalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradient1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(764, Short.MAX_VALUE))
        );
        jPanelGradient1Layout.setVerticalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradient1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_headerLayout = new javax.swing.GroupLayout(pn_header);
        pn_header.setLayout(pn_headerLayout);
        pn_headerLayout.setHorizontalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_headerLayout.setVerticalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pn_header, java.awt.BorderLayout.PAGE_START);

        pn_sideBar.setBackground(new java.awt.Color(255, 255, 255));
        pn_sideBar.setPreferredSize(new java.awt.Dimension(200, 450));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu.setForeground(new java.awt.Color(125, 0, 5));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        javax.swing.GroupLayout pn_sideBarLayout = new javax.swing.GroupLayout(pn_sideBar);
        pn_sideBar.setLayout(pn_sideBarLayout);
        pn_sideBarLayout.setHorizontalGroup(
            pn_sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pn_sideBarLayout.setVerticalGroup(
            pn_sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        getContentPane().add(pn_sideBar, java.awt.BorderLayout.LINE_START);

        pn_utama.setLayout(new javax.swing.BoxLayout(pn_utama, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//private void customizeComponents() {
//    // Menyesuaikan warna gradien latar belakang pn_header
//    pn_header.setOpaque(true);
//    pn_header.setBackground( Color.BLACK); // Set alpha to 0 for transparency
//
//    // Menambahkan metode paintComponent untuk menggambar gradien
//    pn_header = new JPanel() {
//        @Override
//        protected void paintComponent(Graphics g) {
//            super.paintComponent(g);
//
//            // Membuat warna gradien dari putih (FFFFFF) ke merah tua (7D0005)
//            GradientPaint gradient = new GradientPaint(
//                0, 0, new Color(255, 255, 255), // Warna awal (putih)
//                0, getHeight(), new Color(125, 0, 5) // Warna akhir (merah tua)
//            );
//
//            // Menggunakan Graphics2D untuk menggambar gradien
//            Graphics2D g2d = (Graphics2D) g;
//            g2d.setPaint(gradient);
//            g2d.fillRect(0, 0, getWidth(), getHeight());
//        }
//    };
//
//    // Tambahkan penyesuaian lainnya di sini
//}

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        form_Login loginForm = new form_Login();
//
//        // Set the login form to be visible
//        loginForm.setVisible(true);
//
//        // Disable the visibility of the main menu temporarily
//        this.setVisible(false);
//
//        // Add an ActionListener to the login form
//        loginForm.addLoginSuccessListener((ActionEvent e) -> {
//            // This will be executed when the user successfully logs in
//            // Make the main menu visible again
//            Main_Menu_KASIR.this.setVisible(true);
//
//            // Dispose the login form if it's no longer needed
//            loginForm.dispose();
//        });
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private main_menu.JPanelGradient jPanelGradient1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_header;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_sideBar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconBeranda = new ImageIcon(getClass().getClassLoader().getResource("image/home.png"));
        ImageIcon iconMenu = new ImageIcon(getClass().getClassLoader().getResource("image/menu.png"));
        ImageIcon iconLaporan = new ImageIcon(getClass().getClassLoader().getResource("image/laporan.png"));
        ImageIcon iconLogout = new ImageIcon(getClass().getClassLoader().getResource("image/logout.png"));

        MenuItem makanan = new MenuItem(null, true, null, "Makanan", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Menu_Makanan());
            pn_utama.repaint();
            pn_utama.revalidate();
        });
        MenuItem minuman = new MenuItem(null, true, null, "Minuman", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Menu_Minuman());
            pn_utama.repaint();
            pn_utama.revalidate();
        });
        MenuItem meja = new MenuItem(null, true, null, "Meja", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Meja());
            pn_utama.repaint();
            pn_utama.revalidate();
        });

        MenuItem beranda = new MenuItem(iconBeranda, false, null, "Beranda", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Beranda());
            pn_utama.repaint();
            pn_utama.revalidate();
        });
        MenuItem menu = new MenuItem(iconMenu, false, null, "Menu", null, makanan, minuman, meja);
        MenuItem laporan = new MenuItem(iconLaporan, false, null, "Laporan", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Laporan());
            pn_utama.repaint();
            pn_utama.revalidate();
        });
        MenuItem logout = new MenuItem(iconLogout, false, null, "Keluar", (ActionEvent e) -> {
            int option = JOptionPane.showConfirmDialog(
                    null,
                    "Apakah Anda yakin ingin keluar?",
                    "Konfirmasi Keluar",
                    JOptionPane.YES_NO_OPTION
            );
            
            // Check user's choice
            if (option == JOptionPane.YES_OPTION) {
                Form_Login fl = new Form_Login();
                dispose();
                fl.setVisible(true);
            }
        });

        addMenu(beranda, menu, laporan, logout);

    }

    private void addMenu(MenuItem... menu) {
        for (MenuItem menu1 : menu) {
            pn_menu.add(menu1);
            ArrayList<MenuItem> subMenu = menu1.getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }
        }
        pn_menu.revalidate();
    }
}
