package menu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.DTDConstants;
import koneksi.Koneksi;
import model.Makanan;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author wandy
 */
public class Menu_Makanan_Kasir extends javax.swing.JPanel {

    private DefaultTableModel table;
    private Makanan mkn = new Makanan();

    /**
     * Creates new form Menu_Makanan
     */
    public Menu_Makanan_Kasir() {
        initComponents();
        table = new DefaultTableModel();
        dataMakanan.setModel(table);

        table.addColumn("Id");
        table.addColumn("Nama");
        table.addColumn("Kategori");
        table.addColumn("Stok");
        table.addColumn("Harga");
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        DataMenuMakanan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataMakanan = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        jScrollPane1.setViewportView(dataMakanan);

        javax.swing.GroupLayout DataMenuMakananLayout = new javax.swing.GroupLayout(DataMenuMakanan);
        DataMenuMakanan.setLayout(DataMenuMakananLayout);
        DataMenuMakananLayout.setHorizontalGroup(
            DataMenuMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataMenuMakananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        DataMenuMakananLayout.setVerticalGroup(
            DataMenuMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataMenuMakananLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        MainPanel.add(DataMenuMakanan, "card2");

        add(MainPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    public void loadData() {
        table.getDataVector().removeAllElements();
        table.fireTableDataChanged();
        mkn.loadData(table);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataMenuMakanan;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTable dataMakanan;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
