/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menu;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Minuman;

/**
 *
 * @author fauzanramadhana
 */
public class Menu_Minuman extends javax.swing.JPanel {
    
    private DefaultTableModel table;
    private Minuman mnm = new Minuman();

    /**
     * Creates new form Menu_Minuman
     */
    public Menu_Minuman() {
        initComponents();
        table = new DefaultTableModel();
        DataMinuman.setModel(table);

        table.addColumn("Id");
        table.addColumn("Nama");
        table.addColumn("Kategori");
        table.addColumn("Stok");
        table.addColumn("Harga");
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        DataMenuMinuman = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataMinuman = new javax.swing.JTable();
        TambahMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tvNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tvStok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tvHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tvKategori = new javax.swing.JTextField();
        PerbaruiMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPerbarui = new javax.swing.JButton();
        btnBatal1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tvId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tvNama1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tvStok1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tvHarga1 = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(724, 455));
        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        DataMinuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(DataMinuman);

        javax.swing.GroupLayout DataMenuMinumanLayout = new javax.swing.GroupLayout(DataMenuMinuman);
        DataMenuMinuman.setLayout(DataMenuMinumanLayout);
        DataMenuMinumanLayout.setHorizontalGroup(
            DataMenuMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataMenuMinumanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataMenuMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataMenuMinumanLayout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        DataMenuMinumanLayout.setVerticalGroup(
            DataMenuMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataMenuMinumanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataMenuMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        MainPanel.add(DataMenuMinuman, "card2");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(btnBatal)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Nama Minuman");

        tvNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvNamaActionPerformed(evt);
            }
        });

        jLabel3.setText("Stok");

        tvStok.setText("0");
        tvStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvStokActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga");

        tvHarga.setText("0");
        tvHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvHargaActionPerformed(evt);
            }
        });

        jLabel5.setText("Kategori");

        tvKategori.setEditable(false);
        tvKategori.setText("Minuman");
        tvKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TambahMenuLayout = new javax.swing.GroupLayout(TambahMenu);
        TambahMenu.setLayout(TambahMenuLayout);
        TambahMenuLayout.setHorizontalGroup(
            TambahMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tvNama)
            .addComponent(tvStok)
            .addComponent(tvHarga)
            .addGroup(TambahMenuLayout.createSequentialGroup()
                .addGroup(TambahMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(0, 559, Short.MAX_VALUE))
            .addComponent(tvKategori)
        );
        TambahMenuLayout.setVerticalGroup(
            TambahMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 206, Short.MAX_VALUE))
        );

        MainPanel.add(TambahMenu, "card3");

        btnPerbarui.setText("Perbarui");
        btnPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiActionPerformed(evt);
            }
        });

        btnBatal1.setText("Batal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnPerbarui)
                .addGap(18, 18, 18)
                .addComponent(btnBatal1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPerbarui)
                    .addComponent(btnBatal1))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel6.setText("ID");

        jLabel7.setText("Nama Minuman");

        jLabel8.setText("Stok");

        tvStok1.setText("0");
        tvStok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvStok1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Harga");

        tvHarga1.setText("0");

        javax.swing.GroupLayout PerbaruiMenuLayout = new javax.swing.GroupLayout(PerbaruiMenu);
        PerbaruiMenu.setLayout(PerbaruiMenuLayout);
        PerbaruiMenuLayout.setHorizontalGroup(
            PerbaruiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerbaruiMenuLayout.createSequentialGroup()
                .addGroup(PerbaruiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tvHarga1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addComponent(tvStok1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tvNama1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tvId, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 96, Short.MAX_VALUE))
        );
        PerbaruiMenuLayout.setVerticalGroup(
            PerbaruiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerbaruiMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvStok1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tvHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        MainPanel.add(PerbaruiMenu, "card4");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tvNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvNamaActionPerformed

    private void tvStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvStokActionPerformed

    private void tvHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvHargaActionPerformed

    private void tvKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvKategoriActionPerformed

    private void btnPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiActionPerformed
        String nama = tvNama1.getText();
        int stok = Integer.parseInt(tvStok1.getText());
        int harga = Integer.parseInt(tvHarga1.getText());
        int id = Integer.parseInt(tvId.getText());
        int i = mnm.updateData(nama, stok, harga, id);
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
                MainPanel.removeAll();
                MainPanel.repaint();
                MainPanel.revalidate();
                MainPanel.add(DataMenuMinuman);
                MainPanel.repaint();
                MainPanel.revalidate();
                loadData();
            }
    }//GEN-LAST:event_btnPerbaruiActionPerformed

    private void tvStok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvStok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvStok1ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        tvNama.setText("");
        tvStok.setText("0");
        tvHarga.setText("0");
        MainPanel.add(TambahMenu);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = DataMinuman.getSelectedRow();
        if (selectedRow != -1) {
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();
            MainPanel.add(PerbaruiMenu);
            MainPanel.repaint();
            MainPanel.revalidate();
            tvId.setText(String.valueOf(DataMinuman.getValueAt(selectedRow, 0)));
            tvNama1.setText(String.valueOf(DataMinuman.getValueAt(selectedRow, 1)));
            tvStok1.setText(String.valueOf(DataMinuman.getValueAt(selectedRow, 3)));  
            tvHarga1.setText(String.valueOf(DataMinuman.getValueAt(selectedRow, 4)));
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan diperbarui!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        MainPanel.add(DataMenuMinuman);
        MainPanel.repaint();
        MainPanel.revalidate();
        loadData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = tvNama.getText();
        int stok = Integer.parseInt(tvStok.getText());
        int harga = Integer.parseInt(tvHarga.getText());
        String kategori = (String) tvKategori.getText();

        if (nama.equals("") || stok == 0 || harga == 0 || kategori.equals("")) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            int i = mnm.addData(nama, stok, harga, kategori);
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
                MainPanel.removeAll();
                MainPanel.repaint();
                MainPanel.revalidate();
                MainPanel.add(DataMenuMinuman);
                MainPanel.repaint();
                MainPanel.revalidate();
                loadData();
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = DataMinuman.getSelectedRow();
        if (selectedRow != -1) {
            int option = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                mnm.deleteData((int) DataMinuman.getValueAt(selectedRow, 0));
                loadData();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    public void loadData() {
        table.getDataVector().removeAllElements();
        table.fireTableDataChanged();
        mnm.loadData(table);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataMenuMinuman;
    private javax.swing.JTable DataMinuman;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PerbaruiMenu;
    private javax.swing.JPanel TambahMenu;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tvHarga;
    private javax.swing.JTextField tvHarga1;
    private javax.swing.JTextField tvId;
    private javax.swing.JTextField tvKategori;
    private javax.swing.JTextField tvNama;
    private javax.swing.JTextField tvNama1;
    private javax.swing.JTextField tvStok;
    private javax.swing.JTextField tvStok1;
    // End of variables declaration//GEN-END:variables
}
