
import Laporan.Laporan;
import Transaksi.Transaksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import menu.Menu_Makanan;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import menu.Meja;
import menu.Meja_Kasir;
import menu.Menu_Makanan_Kasir;
import menu.Menu_Minuman;
import menu.Menu_Minuman_Kasir;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author fauzanramadhana
 */
public class Main_Menu_KASIR extends javax.swing.JFrame {

    public Main_Menu_KASIR() {
        initComponents();
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pn_sideBar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        pn_content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_header.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Navbar (1).png"))); // NOI18N

        javax.swing.GroupLayout pn_headerLayout = new javax.swing.GroupLayout(pn_header);
        pn_header.setLayout(pn_headerLayout);
        pn_headerLayout.setHorizontalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_headerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(776, Short.MAX_VALUE))
        );
        pn_headerLayout.setVerticalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(pn_header, java.awt.BorderLayout.PAGE_START);

        pn_sideBar.setBackground(new java.awt.Color(255, 255, 255));
        pn_sideBar.setPreferredSize(new java.awt.Dimension(200, 450));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        javax.swing.GroupLayout pn_sideBarLayout = new javax.swing.GroupLayout(pn_sideBar);
        pn_sideBar.setLayout(pn_sideBarLayout);
        pn_sideBarLayout.setHorizontalGroup(
            pn_sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pn_sideBarLayout.setVerticalGroup(
            pn_sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        getContentPane().add(pn_sideBar, java.awt.BorderLayout.LINE_START);

        pn_utama.setLayout(new javax.swing.BoxLayout(pn_utama, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(900, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        form_Login loginForm = new form_Login();
//
//        // Set the login form to be visible
//        loginForm.setVisible(true);
//
//        // Disable the visibility of the main menu temporarily
//        this.setVisible(false);
//
//        // Add an ActionListener to the login form
//        loginForm.addLoginSuccessListener((ActionEvent e) -> {
//            // This will be executed when the user successfully logs in
//            // Make the main menu visible again
//            Main_Menu_KASIR.this.setVisible(true);
//
//            // Dispose the login form if it's no longer needed
//            loginForm.dispose();
//        });
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu_KASIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu_KASIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu_KASIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu_KASIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main_Menu_KASIR().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_header;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_sideBar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconBeranda = new ImageIcon(getClass().getResource("/image/home.png"));
        ImageIcon iconMenu = new ImageIcon(getClass().getResource("/image/Menu.png"));
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/image/transaksi.png"));
        ImageIcon iconLaporan = new ImageIcon(getClass().getResource("/image/laporan.png"));
        ImageIcon iconLogout = new ImageIcon(getClass().getResource("/image/logout.png"));
        ImageIcon iconSub = new ImageIcon(getClass().getResource("/image/subIcon.png"));

        MenuItem makanan = new MenuItem(null, true, iconSub, "Makanan", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Menu_Makanan_Kasir());
            pn_utama.repaint();
            pn_utama.revalidate();
        });
        MenuItem minuman = new MenuItem(null, true, iconSub, "Minuman", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Menu_Minuman_Kasir());
            pn_utama.repaint();
            pn_utama.revalidate();
        });
        MenuItem meja = new MenuItem(null, true, iconSub, "Meja", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Meja_Kasir());
            pn_utama.repaint();
            pn_utama.revalidate();
        });

        MenuItem beranda = new MenuItem(iconBeranda, false, null, "Beranda", null);
        MenuItem menu = new MenuItem(iconMenu, false, null, "Menu", null, makanan, minuman, meja);
        MenuItem transaksi = new MenuItem(iconTransaksi, false, null, "Transaksi", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Transaksi());
            pn_utama.repaint();
            pn_utama.revalidate();
        });
        MenuItem laporan = new MenuItem(iconLaporan, false, null, "Laporan", (ActionEvent e) -> {
            pn_utama.removeAll(); // Clear existing components
            pn_utama.add(new Laporan());
            pn_utama.repaint();
            pn_utama.revalidate();
        });
        MenuItem logout = new MenuItem(iconLogout, false, null, "Keluar", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int option = JOptionPane.showConfirmDialog(
                        null,
                        "Apakah Anda yakin ingin keluar?",
                        "Konfirmasi Keluar",
                        JOptionPane.YES_NO_OPTION
                );

                // Check user's choice
                if (option == JOptionPane.YES_OPTION) {

                    handleLogoutOrExit();
                }
            }

            private void handleLogoutOrExit() {
                System.exit(0);
            }
        });

        addMenu(beranda, menu, transaksi, laporan, logout);

    }

    private void addMenu(MenuItem... menu) {
        for (MenuItem menu1 : menu) {
            pn_menu.add(menu1);
            ArrayList<MenuItem> subMenu = menu1.getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }
        }
        pn_menu.revalidate();
    }
}
